import { StyleSheet } from "react-native";
export const global = StyleSheet.create({
  container: {
    width: "100%",
    flex: 1,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "flex-start",
  },
  wrapper: {
    paddingLeft: 10,
    paddingRight: 20,
    marginVertical: 15,
    flex: 1,
  },
  flex: {
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  inputGroup: {
    width: "100%",
    color: "#202124",
    borderWidth: 1,
    borderColor: "transparent",
    borderRadius: 6,
    marginBottom: 12,
    paddingHorizontal: 22,
    paddingVertical: 15,
    backgroundColor: "white",
    shadowColor: "#fff",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.5,
    elevation: 2,
  },
  err: {
    borderColor: "rgb(217, 48, 37)",
  },
  titleCauHoi: {
    textAlign: "left",
    width: "100%",
    fontWeight: "500",
    fontSize: 20,
  },
  btn: {
    backgroundColor: "#1E88E5",
    color: "white",
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 15,
    shadowColor: "#fff",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.5,
    elevation: 2,
  },
  btnHide: {
    backgroundColor: "#EEEEEE",
    color: "white",
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  btnText: {
    color: "white",
    fontSize: 14,
    textTransform: "uppercase",
    textAlign: "center",
  },
  box: {
    width: "100%",
    color: "#202124",
    borderRadius: 6,
    marginBottom: 12,
    paddingHorizontal: 22,
    paddingVertical: 15,
    backgroundColor: "white",
    shadowColor: "#fff",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.5,
    elevation: 2,
  },
  boxTitle: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 5,
    borderBottomColor: "#eeeeee",
    borderBottomWidth: 1,
  },
  boxDes: {
    minHeight: 32,
    alignItems: "center",
    flexDirection: "row",
  },
});
